import { NavBar, Footer } from "@/components";
import "./globals.css";

export const metadata = {
  title: "Learning nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <NavBar />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
